_wandb:
    value:
        cli_version: 0.22.2
        e:
            fulnm65jftct9z38sqguz9uq9jdoiewg:
                codePath: main.py
                codePathLocal: main.py
                email: 2220761584@qq.com
                executable: D:\EEG\egg_encoder\.venv\Scripts\python.exe
                git:
                    commit: 7b7554c4517a42ddbf07359e9549e119f4b6dfa8
                    remote: "\x96\x96https://github.com/qazwsx2323ppp/EEG_encoder.git"
                host: DESKTOP-G642N6B
                os: Windows-10-10.0.26100-SP0
                program: D:\EEG\egg_encoder\main.py
                python: CPython 3.10.10
                root: D:\EEG\egg_encoder
                startedAt: "2025-10-21T07:28:50.602830Z"
                writerId: fulnm65jftct9z38sqguz9uq9jdoiewg
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 5
                - 32
                - 50
                - 53
            "2":
                - 1
                - 5
                - 32
                - 50
                - 53
            "3":
                - 13
                - 16
            "4": 3.10.10
            "5": 0.22.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
data:
    value:
        eeg_path: D:\EEG\egg_encoder\data\EEG_data\eeg_55_95_std.pth
        image_vec_path: D:\EEG\egg_encoder\data\image_vectors.npy
        splits_path: D:\EEG\egg_encoder\data\EEG_data\block_splits_by_image_all.pth
        text_vec_path: D:\EEG\egg_encoder\data\text_vectors.npy
model:
    value:
        channel_merge: linear
        drop_prob: 0.5
        embedding_dim: 512
        encoder_name: braindecode_shallow
        filter_time_length: 25
        model_name: eeg_encoder
        n_channels: 128
        n_filters_spat: 40
        n_filters_time: 40
        n_heads: 8
        n_linear_layers: 1
        n_samples: 440
        pool_time_length: 75
        pool_time_stride: 15
training:
    value:
        alpha: 0.5
        batch_size: 64
        device: cuda
        epochs: 100
        learning_rate: 0.0001
        num_workers: 4
        temperature: 0.1
wandb:
    value:
        entity: null
        name: eeg_triplet_train
        project: EEG_Decoupling
