dataset:
  n_recordings: 2993
  processed_categories: "all"
  target_name: "report"
  preprocessing:
    sfreq: 100
    n_minutes: 2
    input_window_samples: 1200


eegclip:
  lr: 0.005
  weight_decay: 0.0005
  dropout: 0.1
  projected_emb_dim: 64
  num_fc_layers: 2
  eeg_encoder:
    pretrained: false
    trainable: true
    emb_dim: 1024
    n_preds_per_input: 519
    n_eeg_channels: 21
  text_encoder:
    pretrained: true
    trainable: false
    emb_dim: 1024
    pretrained_name: WhereIsAI/UAE-Large-V1
    string_sampling: false
    lr_frac_lm: 0
    max_token_len: 512
  contrastive_loss:
    func: clip
    temperature: 1

training:
  seed: 20210325
  n_epochs: 20
  batch_size: 512
  num_workers: 20
  cross_validation: false
  n_folds: 5
  fold_idx: 0