# configs/triplet_config.yaml

# 1. Hydra 默认设置
defaults:
  - _self_
  - override hydra/launcher: slurm # 如果在集群上运行，否则可以注释掉

# 2. WandB 日志 (推荐使用)
wandb:
  project: "EEG_Decoupling"
  entity: null # 替换为您的 wandb 用户名
  name: "eeg_triplet_train"

# 3. 数据路径
# !! 必须修改这里的路径，指向您本地的数据 !!
data:
    root: ${hydra:runtime.cwd}
    eeg_path: ${data.root}/data/EEG_data/eeg_55_95_std.pth
    image_vec_path: ${data.root}/data/image_vectors.npy
    text_vec_path: ${data.root}/data/text_vectors.npy
    splits_path: ${data.root}/data/EEG_data/block_splits_by_image_all.pth

# 4. 训练参数
training:
  epochs: 100
  batch_size: 64
  learning_rate: 0.0001
  num_workers: 4
  device: "cuda" # 'cuda' or 'cpu'

  # 损失函数权重 (alpha * loss_img + (1-alpha) * loss_txt)
  alpha: 0.5

  # InfoNCE 损失函数的温度参数
  temperature: 0.1

# 5. EEG 编码器模型参数
#    这些参数来自 EEG-CLIP 仓库，您可以直接使用
model:
  model_name: 'eeg_encoder'

  # EEG 编码器参数
  n_linear_layers: 1
  channel_merge: 'linear' # 'linear' or 'attention'
  n_heads: 8

  # 确保这个维度与您的 image/text 向量维度一致
  # e.g., 512 for 'clip-vit-base-patch32'
  embedding_dim: 512

  # EEG 信号参数 (必须与数据匹配)
  n_channels: 128
  n_samples: 440

  # 编码器主干网络 (来自 clip_models.py)
  encoder_name: 'braindecode_shallow' # 'braindecode_shallow' 或 'braindecode_deep'

  # 卷积层参数
  n_filters_time: 40
  filter_time_length: 25
  n_filters_spat: 40
  pool_time_length: 75
  pool_time_stride: 15
  drop_prob: 0.5

# 6. Hydra 运行设置
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}